version: '3.8'

networks: 
    tig-net:
        driver: bridge

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "iot"
            INFLUXDB_ADMIN_USER: "iotlnu"
            INFLUXDB_ADMIN_PASSWORD: "micropython"
        networks: 
            - tig-net
        volumes:
            - "./influxdb/data:/var/lib/influxdb"

    grafana:
        image: grafana/grafana:7.1.3
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        networks: 
            - tig-net
        restart: always        

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        restart: unless-stopped
        tty: true
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "iot"
        depends_on: 
          - "influxdb"
        volumes:
          - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
        networks: 
          - tig-net
        privileged: true