version: '3.9'

networks: 
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
    influxdb:
        image: influxdb:1.8.6
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "iot"
            INFLUXDB_ADMIN_USER: "root"
            INFLUXDB_ADMIN_PASSWORD: "root"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/influxdb